### ISSUE TITLE
Fav Button Throwing Exception

### ISSUE THREAD

**Issue by tanjimanasreen** [sandiwinter/RealEstateAppKit#1]
Hi, 
We bought this [application kit](https://codecanyon.net/item/real-estate-app-kit/44042629) from the codecanyon. We set up the wp backend in our server according to your given instructions. Currently, the Fav Button on the Listings Screens is not working. Upon pressing the button, it is throwing `internal_server_error` along with the following error log on the server:

`PHP Fatal error:  Uncaught Error: Call to a member function model() on null in C:\\xampp\\htdocs\\wordpress-doc\\wp-content\\plugins\\wdk-api\\wdk-api.php:876\nStack trace:\n#0 C:\\xampp\\htdocs\\wordpress-doc\\wp-includes\\rest-api\\class-wp-rest-server.php(1181): wdk_post_listing_favorite(Object(WP_REST_Request))\n#1 C:\\xampp\\htdocs\\wordpress-doc\\wp-includes\\rest-api\\class-wp-rest-server.php(1028): WP_REST_Server->respond_to_request(Object(WP_REST_Request), '/wdk/v1/listing...', Array, NULL)\n#2 C:\\xampp\\htdocs\\wordpress-doc\\wp-includes\\rest-api\\class-wp-rest-server.php(442): WP_REST_Server->dispatch(Object(WP_REST_Request))\n#3 C:\\xampp\\htdocs\\wordpress-doc\\wp-includes\\rest-api.php(410): WP_REST_Server->serve_request('/wdk/v1/listing...')\n#4 C:\\xampp\\htdocs\\wordpress-doc\\wp-includes\\class-wp-hook.php(308): rest_api_loaded(Object(WP))\n#5 C:\\xampp\\htdocs\\wordpress-doc\\wp-includes\\class-wp-hook.php(332): WP_Hook->apply_filters('', Array)\n#6 C:\\xampp\\htdocs\\wordpress-doc\\wp-includes\\plugin.php(565): WP_Hook->do_action(Array)\n#7 C:\\xampp\\htdocs\\wordpress-doc\\wp-includes\\class-wp.php(399): do_action_ref_array('parse_request', Array)\n#8 C:\\xampp\\htdocs\\wordpress-doc\\wp-includes\\class-wp.php(780): WP->parse_request('')\n#9 C:\\xampp\\htdocs\\wordpress-doc\\wp-includes\\functions.php(1334): WP->main('')\n#10 C:\\xampp\\htdocs\\wordpress-doc\\wp-blog-header.php(16): wp()\n#11 C:\\xampp\\htdocs\\wordpress-doc\\index.php(17): require('C:\\\\xampp\\\\htdocs...')\n#12 {main}\n  thrown in C:\\xampp\\htdocs\\wordpress-doc\\wp-content\\plugins\\wdk-api\\wdk-api.php on line 876`

Also, in the WordPress Plugins section, it is saying we need to provide a license key for WDK Favorites, but we weren't provided any keys with our purchase. 

We highly appreciate your help. Thank you.

**Comment by sandiwinter** [comment]
Hi,

Please provide all info as suggested here so we can check in detail what causing issue:

https://github.com/sandiwinter/RealEstateAppKit/wiki/Support

Try install wp solution on real server, We will need also cpanel login to investigate in detail and quickly add fix if needed.

You are welcome!
